[project]
name = "vibeusage"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Josh Thomas", email = "josh@joshthomas.dev" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
vibeusage = "vibeusage:main"

[build-system]
requires = ["uv_build>=0.9.0,<0.10.0"]
build-backend = "uv_build"
